require("devsallsa.set")
require("devsallsa.remap")
-- require("devsallsa.packer")
-- require("devsallsa.cmp-tabnine")
-- require("devsallsa.nvim-cmp")
-- require("devsallsa.mason")
-- require("devsallsa.lsp")
-- require("devsallsa.null-ls")
-- require("devsallsa.nvim-treesitter")
-- require("devsallsa.nvim-lightbulb")
-- require("devsallsa.telescope")
-- require("devsallsa.which-key")
-- require("devsallsa.nvim-autopairs")
require("devsallsa.autocmd")
